<div id="content">
  <div id="dialogDiv"></div>
  <div class="result">
    <img src="" alt="result image" style="height: 100%;"/>
  </div>
  <div id="contentPanel">
    <div id="object1" class="object"></div>
    <div id="object2" class="object"></div>

    <div id="scorePanel">
      <div id="scoreGood">
        <img src="../img/smileFace.png" alt="good answers" style="height: 25px;"/>
        <div>0</div>
      </div>
      <div id="scoreBad">
        <img src="../img/sadFace.png" alt="bad answers" style="height: 25px;"/>
        <div>0</div>
      </div>
    </div>
  </div>
</div>

<footer>
  © 2020 All rights reserved. Teodor GUTAN.
</footer>

<script type="text/javascript">
  $(function() {
    go();
  });
</script>
