<div id="content">
  <div class="result">
    <img src="" alt="result image" style="height: 100%;"/>
  </div>
  <div id="contentPanel">
    <div id="actionPanel">
      <div class="objects-container">
        <div id="object1" class="object">
          <img alt="image1" src=""/>
        </div>
        <div style="width: 30px;"></div>
        <div id="object2" class="object">
          <img alt="image2" src=""/>
        </div>
      </div>
    </div>
    <div id="scoreGood" style="padding-left: 30px;">
      <img src="../img/smileFace.png" alt="good answers" style="height: 25px;"/>
      <div>0</div>
    </div>
    <div id="scoreBad" style="margin: 30px 0 0 0; padding-left: 30px;">
      <img src="../img/sadFace.png" alt="bad answers" style="height: 25px;"/>
      <div>0</div>
    </div>
  </div>
</div>

<footer>
  © 2020 All rights reserved. Teodor GUTAN.
</footer>

<script type="text/javascript">
  $(function() {
    go();
  });
</script>
